name: AFantasyStopTransfer
author: Enrick3344
version: 0.1
api:
- 3.0.0-ALPHA7
- 3.0.0-ALPHA8
- 3.0.0-ALPHA9
- 3.0.0-ALPHA10
main: FantasyStopTransfer\Main

permissions:
  funworldtransfer.bypass:
    default: false
